package report

import java.time.LocalDate
import queries.AttributionRow

/** Minimal HTML escaping for text interpolated into the document. */
private fun esc(s: String): String = s
    .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    .replace("\"", "&quot;").replace("'", "&#39;")

/** Escape for a double-quoted JS string literal (the chart labels). */
private fun jsString(s: String): String =
    "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("<", "\\u003C") + "\""

/**
 * Stretch goal: a single static HTML file with a Brinson-Fachler waterfall chart
 * (vanilla JS + Chart.js floating bars from a CDN). No server, no build step.
 *
 * All numeric formatting goes through [fmt] (Locale.ROOT): the bar arrays are *parsed by
 * the browser*, so a decimal comma from the host locale would corrupt the chart data.
 */
fun buildHtmlReport(
    portfolioName: String,
    from: LocalDate,
    to: LocalDate,
    rows: List<AttributionRow>,
): String {
    val sorted = rows.sortedByDescending { it.total }
    val labels = sorted.map { jsString(it.sector) } + jsString("Active return")
    // Waterfall: each sector's total effect stacks cumulatively into the active return.
    val steps = buildList {
        var running = 0.0
        for (r in sorted) {
            add(Triple(running, running + r.total, r))
            running += r.total
        }
    }
    val totalActive = steps.lastOrNull()?.second ?: 0.0
    val bars = steps.joinToString(",") { (a, b, _) -> "[%.4f, %.4f]".fmt(a * 1e4, b * 1e4) } +
        ",[0, %.4f]".fmt(totalActive * 1e4)
    val colors = steps.joinToString(",") { (_, _, r) ->
        if (r.total >= 0) "\"rgba(110,155,106,0.85)\"" else "\"rgba(198,93,73,0.85)\""
    } + ",\"rgba(41,38,29,0.88)\""
    val tableRows = sorted.joinToString("\n") { r ->
        "<tr><td>${esc(r.sector)}</td><td>%.1f%%</td><td>%.1f%%</td><td>%+.1f</td><td>%+.1f</td><td>%+.1f</td><td><b>%+.1f</b></td></tr>"
            .fmt(
                r.avgPortfolioWeight * 100, r.avgBenchmarkWeight * 100,
                r.allocation * 1e4, r.selection * 1e4, r.interaction * 1e4, r.total * 1e4,
            )
    }
    val title = esc(portfolioName)
    return """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>$title — Brinson-Fachler attribution</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #FAF9F5; margin: 2rem auto; max-width: 960px; color: #29261D; }
  h1 { font-size: 1.3rem; } .sub { color: #6b7280; margin-bottom: 1.5rem; }
  table { border-collapse: collapse; margin-top: 2rem; width: 100%; font-size: 0.9rem; }
  th, td { padding: 6px 10px; text-align: right; border-bottom: 1px solid #e5e7eb; }
  th:first-child, td:first-child { text-align: left; }
</style>
</head>
<body>
<h1>$title — Brinson-Fachler attribution waterfall</h1>
<div class="sub">$from → $to · Cariño-linked daily effects, basis points · generated by <code>brinson report --html</code></div>
<canvas id="waterfall" height="120"></canvas>
<table>
<thead><tr><th>Sector</th><th>wp</th><th>wb</th><th>Allocation</th><th>Selection</th><th>Interaction</th><th>Total</th></tr></thead>
<tbody>
$tableRows
</tbody>
</table>
<script>
new Chart(document.getElementById("waterfall"), {
  type: "bar",
  data: {
    labels: [${labels.joinToString(",")}],
    datasets: [{ data: [$bars], backgroundColor: [$colors], borderSkipped: false }]
  },
  options: {
    plugins: {
      legend: { display: false },
      tooltip: { callbacks: { label: c => (c.raw[1] - c.raw[0]).toFixed(1) + " bps" } }
    },
    scales: {
      y: { title: { display: true, text: "active return (bps)" } },
      x: { ticks: { maxRotation: 60, minRotation: 45 } }
    }
  }
});
</script>
</body>
</html>
    """.trimIndent()
}
